### ISSUE TITLE
torch.gt return BoolType value from 1.2.0

### ISSUE THREAD

**Issue by JasonDoingGreat** [DeLightCMU/RSC#1]
Since Pytorch 1.2.0, `torch.gt` returns `BoolType` instead of `ByteType` which will cause error on https://github.com/DeLightCMU/RSC/blob/2622a6c1cefc4b6c7c39bb95c457a2a36d27dae9/models/resnet.py#L170 

Pls kindly take a look and add some requirements for pytorch version

**Comment by Justinhzy** [comment]
Hi, sorry for the late reply. I use pytorch 1.1.0 or 1.0.1. I will fix the bug for higher pytorch version. Thanks for your advice.

**Comment by BurningFr** [comment]
Hi, thank you for answering my question!

I find there are some missing files in ./models (alexnet.py). I run the 'train.py' on my server and the reproduction results cannot achieve as high as the paper released (PACS dataset on resnet18). If I miss something important? I have annotated some codes in class 'JigsawNewDataset' which are for jigsaw data generate process to run RSC model.

My reproduction results is 79.45% for Sketch and 80.22% for Art Painting.

**Comment by talhazaidi13** [comment]
Hi.
 Did you update the code for higher versions of PyTorch to fix the same bug? I am getting the same problem in runtime.

**Comment by JasonDoingGreat** [comment]
> Hi.
> Did you update the code for higher versions of PyTorch to fix the same bug? I am getting the same problem in runtime.

A simple walk around is to add `.long()` at the end

https://github.com/DeLightCMU/RSC/blob/c46568709965ae5a1ea92e95ab6ae27cc190eb0d/models/resnet.py#L136

**Comment by Justinhzy** [comment]
@JasonDoingGreat Thanks. I will fix it.

**Comment by talhazaidi13** [comment]
it works now, Thanks.
