### ISSUE TITLE
JigsawNewDataset Class error 

### ISSUE THREAD

**Issue by talhazaidi13** [DeLightCMU/RSC#6]
Hi,
 I am trying to run the code, but i am getting an error while executing the following line inside the JigsawNewDataset Class 
`  all_perm = np.load('permutations_%d.npy' % (classes))

I have looked through all the files and there isn't a file called permuations.npy as part of the code or the dataset. I have looked through the code and can't seem to find a line that generates the said file. 

Help would be appreciated

**Comment by Johnzhangt** [comment]
This file is generated reused from another Github Code. You can take a reference at https://github.com/fmcarlucci/JigenDG

**Comment by talhazaidi13** [comment]
Thankyou so much, I get these files now

**Comment by Justinhzy** [comment]
Hi, sorry about the error. please annotate the code all_perm = np.load('permutations_%d.npy' % (classes)).
