### ISSUE TITLE
Why not choose the grad of x_new_4 directly for spatial _mean?

### ISSUE THREAD

**Issue by gkyustc** [DeLightCMU/RSC#7]
https://github.com/DeLightCMU/RSC/blob/c46568709965ae5a1ea92e95ab6ae27cc190eb0d/models/resnet.py#L95

**Comment by YijinHuang** [comment]
Because all gradient of x_new_4 in spatial will be the same. You can see #3

**Comment by gkyustc** [comment]
oh yeah! I didn't notice that! Thanks
