### ISSUE TITLE
Alexnet issue

### ISSUE THREAD

**Issue by talhazaidi13** [DeLightCMU/RSC#8]
Hi,
  I am trying to run the RSC code with the backbone Alexnet model, to get the results reported in table 6. Can I know that you used the same ALEXNET model file which is being used in JigenDG (https://github.com/fmcarlucci/JigenDG) ?

thanks

**Comment by talhazaidi13** [comment]
I tried to use that one but I am getting the following error that 
                               ''AlexNet' object has no attribute 'is_patch_based''
Need your kind support in this regard.

**Comment by zeyihuang** [comment]
Hi, I use the same Alexnet model as Jigen and I will upload it.

**Comment by Justinhzy** [comment]
Hi, I use the same Alexnet in Jigen and I will update it.
